/**
 * This file is a playwright test that verifies that the data analysis features function as they should.
 * They are mostly generated by claude. 
 * TODO : add mocked api for coordinated behavior and textual similarity.
 */
import { test, expect } from './fixtures';
import path from 'path';

const runAllAnalysisTools = async (page) => {
  await page.locator('[data-testid="sna-tab-timelineDistribution"]').click();
  await page
    .locator('[data-testid="sna-run-analysis-button-snaTools_timelineDistributionDescription"]')
    .click();

  await page.locator('[data-testid="sna-tab-accountActivity"]').click();
  await page
    .locator('[data-testid="sna-run-analysis-button-snaTools_accountActivityDescription"]')
    .click();

//   await page.locator('[data-testid="sna-tab-coor"]').click();
//   await page
//     .locator('[data-testid="sna-run-analysis-button-snaTools_coorDescription"]')
//     .click();

  await page.locator('[data-testid="sna-tab-mostMentioned"]').click();
  await page
    .locator('[data-testid="sna-run-analysis-button-snaTools_mostMentionedDescription"]')
    .click();

  await page.locator('[data-testid="sna-tab-hashtagAnalysis"]').click();
  await page
    .locator('[data-testid="sna-run-analysis-button-snaTools_hashtagAnalysisDescription"]')
    .click();

  await page.locator('[data-testid="sna-tab-wordCloud"]').click();
  await page
    .locator('[data-testid="sna-run-analysis-button-snaTools_wordCloudDescription"]')
    .click();

//   await page.locator('[data-testid="sna-tab-textClusters"]').click();
//   await page
//     .locator('[data-testid="sna-run-analysis-button-snaTools_textClustersDescription"]')
//     .click();
};

test("Test tool tittok", async ({
  page,
  authenticatedBetaTesterExtensionId,
}) => {
  await page.goto(
    `chrome-extension://${authenticatedBetaTesterExtensionId}/popup.html#/app/tools/Sna`,
  );

  // Upload TikTok CSV file
  const filePath = path.resolve(
    __dirname,
    "../../tests-assets/TK-TEST-PLAYWRIGHT~TIKTOK_export.csv",
  );
  await page
    .locator('[data-testid="sna-file-upload-input"]')
    .setInputFiles(filePath);

  // Select TikTok as the social media platform in the upload modal
  await page.locator('[data-testid="sna-social-media-icon-tiktok"]').click();

  // Fill in new collection name — handleAddCollection auto-selects it after adding
  await page.locator('[data-testid="sna-new-collection-input"]').fill("TEST-TK");
  await page.locator('[data-testid="sna-add-collection-button"]').click();

  // Confirm upload and wait for collection row to appear in the table
  await page
    .locator('[data-testid="sna-upload-modal-confirm-button"]')
    .click();

  const collectionRow = page.locator('[data-testid^="sna-collection-row-TEST-TK"]');
  await expect(collectionRow).toBeVisible({ timeout: 15000 });

  // Select the collection checkbox
  await collectionRow
    .locator('[data-testid^="sna-collection-checkbox-"]')
    .click();

  await runAllAnalysisTools(page);

  // --- Download CSV (Menu renders in a Portal — use page-level locators) ---
  const dlButton = collectionRow.locator('button[id^="dl_button"]');

  await dlButton.click();
  const downloadCsvPromise = page.waitForEvent("download");
  await page.locator('[data-testid^="sna-download-csv-"]').click();
  await downloadCsvPromise;

  // --- Download JSON ---
  await dlButton.click();
  const downloadJsonPromise = page.waitForEvent("download");
  await page.locator('[data-testid^="sna-download-json-"]').click();
  await downloadJsonPromise;

  // --- Delete the collection ---
  await collectionRow.locator('[data-testid^="sna-delete-button-"]').click();
  await expect(collectionRow).not.toBeVisible({ timeout: 5000 });
});

test("Test tool twitter", async ({
  page,
  authenticatedBetaTesterExtensionId,
}) => {
  await page.goto(
    `chrome-extension://${authenticatedBetaTesterExtensionId}/popup.html#/app/tools/Sna`,
  );

  // Upload Twitter CSV file
  const filePath = path.resolve(
    __dirname,
    "../../tests-assets/TW-TEST-PLAYWRIGHT~TWITTER_export.csv",
  );
  await page
    .locator('[data-testid="sna-file-upload-input"]')
    .setInputFiles(filePath);

  // Select Twitter as the social media platform in the upload modal
  await page.locator('[data-testid="sna-social-media-icon-twitter"]').click();

  // Fill in new collection name — handleAddCollection auto-selects it after adding
  await page.locator('[data-testid="sna-new-collection-input"]').fill("TEST-TW");
  await page.locator('[data-testid="sna-add-collection-button"]').click();

  // Confirm upload and wait for collection row to appear in the table
  await page
    .locator('[data-testid="sna-upload-modal-confirm-button"]')
    .click();

  const collectionRow = page.locator('[data-testid^="sna-collection-row-TEST-TW"]');
  await expect(collectionRow).toBeVisible({ timeout: 15000 });

  // Select the collection checkbox
  await collectionRow
    .locator('[data-testid^="sna-collection-checkbox-"]')
    .click();

  await runAllAnalysisTools(page);

  // --- Download CSV (Menu renders in a Portal — use page-level locators) ---
  const dlButton = collectionRow.locator('button[id^="dl_button"]');

  await dlButton.click();
  const downloadCsvPromise = page.waitForEvent("download");
  await page.locator('[data-testid^="sna-download-csv-"]').click();
  await downloadCsvPromise;

  // --- Download JSON ---
  await dlButton.click();
  const downloadJsonPromise = page.waitForEvent("download");
  await page.locator('[data-testid^="sna-download-json-"]').click();
  await downloadJsonPromise;

  // --- Delete the collection ---
  await collectionRow.locator('[data-testid^="sna-delete-button-"]').click();
  await expect(collectionRow).not.toBeVisible({ timeout: 5000 });
});
