/**
 * TODO : adding a test for the editor in magnifier, even if it's not an emergency because 
 * it's an external component.
 * This file is a playwright test that verifies that the image's features function as they should. 
 * They are mostly generated by codegen, which you can use with the following command : 
 * 
 * node record-playwright.js
 * 
 */
import { test, expect } from './fixtures';
import path from 'path';

test('Test tool magnifier', async ({ page, context, extensionId }) => {
    // Navigate to the demo page
    await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/magnifier`);
    // Accept local storage usage
    await page.getByText("Accept").click();

    // submit input file
    await page.locator('[data-testid="magnifier-input"] input').fill('https://media.sudouest.fr/23190627/1200x600/macron.avif');
    await page.locator('[data-testid="magnifier-submit"]').click();

    // First assertion : is result presne
    await expect(page.locator('[data-testid="magnifier-results"]')).toBeVisible();

    // test cropper
    await page.locator('[data-testid="magnifier-open-cropper"]').click();
    await page.locator('[data-testid="magnifier-close-cropper"]').click();

    // test download
    const downloadPromise = page.waitForEvent('download');
    await page.locator('[data-testid="magnifier-download"]').click();
    const download = await downloadPromise;

    // Counting tabs before reverse search
    const countBefore = context.pages().length;

    // test inversed search
    await page.locator('[data-testid="magnifier-reversesearch"]').first().click();

    // counting tabs after reverse search
    await expect.poll(async () => {
        return context.pages().length;
    }).toBeGreaterThan(countBefore);

    // close the results
    await page.locator('[data-testid="magnifier-close"]').click();

    await expect(page.locator('[data-testid="magnifier-results"]')).toHaveCount(0);
});

test('Test tool metadata image', async ({ page, extensionId }) => {
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/metadata_image`);
  await page.getByText("Accept").click();

  const filePath = path.resolve(__dirname, '../../tests-assets/test-metadata.jpg');

  await page.locator('input[type="file"]').setInputFiles(filePath);

  await page.locator('[data-testid="metadata-submit"]').click();

  await expect (page.locator('[data-testid="c2pa-result"]')).toBeVisible();
});

test('Test tool forensic', async ({ page, extensionId }) => {
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/forensic`);
  await page.getByText("Accept").click();

  await page.locator('[data-testid="forensic-input"] input').fill('https://www.lebigdata.fr/wp-content/uploads/2023/03/macron-pape-ia-deepfake-1050x525.jpg');
  await page.getByTestId('forensic-submit').click();

  await expect (page.locator('[data-testid="forensic-results"]')).toBeVisible();

  await expect (page.locator('[data-testid="forensic-result-image"]')).toBeVisible();
  await expect (page.locator('[data-testid="forensic-results-lenses"]')).toBeVisible();
  await expect (page.locator('[data-testid="forensic-results-filters"]')).toBeVisible();

  await page.getByTestId('forensic-tab-noise').click();
  await page.getByTestId('forensic-tab-family').click();
  await page.getByTestId('forensic-tab-cloning').click();

  await page.getByTestId('forensic-newimage-button').click();
  await expect (page.locator('[data-testid="forensic-results"]')).toHaveCount(0);
});

test('Test tool OCR', async ({ page, context, extensionId }) => {
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/ocr`);
  await page.getByText("Accept").click();

  await page.locator('[data-testid="ocr-input"] input').fill('https://www.rue89strasbourg.com/wp-content/uploads/2024/06/dsc-3582-1920x1280.jpg');
  await page.getByTestId('ocr-submit').click();

  await expect (page.locator('[data-testid="ocr-results"]')).toBeVisible();

  await page.getByTestId('ocr-results-copy').click();
  await page.getByTestId('ocr-results-translate').click();

  await page.getByTestId('ocr-results-yandex').click();
  await page.getByTestId('ocr-results-bing').click();
  await page.getByTestId('ocr-results-google').click();

  await expect.poll(async () => {
    return context.pages().length;
  }).toBe(4);
});

