/**
 * This file is a playwright test that verifies that the video's features function as they should. 
 * They are mostly generated by codegen, which you can use with the following command : 
 * 
 * node record-playwright.js
 * 
 */
import { test, expect } from './fixtures';
import path from 'path';
import singlefileResponse from '../../tests-assets/api-response/singlefile-to-wacz-response';
import mockedChatbotResponse from '../../tests-assets/api-response/chatbot-response';

test('Test tool archive savepagenow', async ({page, authenticatedArchiveExtensionId, context}) => {
    await context.route('**web.archive.org**', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'text/html',
            body: '<html><body>Mocked</body></html>'
        });
    });

    await page.goto(`chrome-extension://${authenticatedArchiveExtensionId}/popup.html#/app/tools/archive`);

    await page.locator('[data-testid="archive-input"] input').fill('https://www.youtube.com/watch?v=QQFgQ1uBQtk');

    await page.getByTestId('archive-submit-savepagenow').click();

    await expect(page.getByTestId('archive-url-archive-card')).toBeVisible();

    const pagesBefore = context.pages();

    await page.getByTestId('archive-internet-archive-button').first().click();

    await expect.poll(async () => context.pages().length).toBeGreaterThan(pagesBefore.length);

    const newPage = context.pages().find(p => !pagesBefore.includes(p));
    await expect(newPage).toHaveURL(/web\.archive\.org/);
});

test('Test tool archive', async ({page, authenticatedArchiveExtensionId}) => {
    const buffer = Buffer.from('fake-wacz-content');

    await page.route('**singlefile**', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify(singlefileResponse)
        });
    });

    await page.route('**scoop**', async (route) => {
        const url = route.request().url();
        const method = route.request().method();

        if (method === 'POST' && url.endsWith('/capture')) {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ id: 'test-capture-id' })
            });
        } else if (url.includes('/capture/download/')) {
            await route.fulfill({
                status: 200,
                contentType: 'application/x-wacz',
                headers: {
                    'Content-Disposition': 'attachment; filename="archive.wacz"',
                    'Content-Length': buffer.length.toString(),
                },
                body: buffer
            });
        } else {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ status: 'COMPLETE' })
            });
        }
    });

    await page.goto(`chrome-extension://${authenticatedArchiveExtensionId}/popup.html#/app/tools/archive`);

    await page.locator('[data-testid="archive-input"] input').fill('https://www.youtube.com/watch?v=QQFgQ1uBQtk');

    await page.getByTestId('archive-submit-wacz').click();

    await expect(page.getByTestId("archive-download-webrecorder-link")).toBeVisible();
    await expect(page.getByTestId("archive-download-webrecorder-guide")).toBeVisible();
    await expect(page.getByTestId("archive-download-webrecorder-tuto")).toBeVisible();

    const filePath = path.resolve(__dirname, '../../tests-assets/test-singlefile-input.html');

    const downloadPromise = page.waitForEvent('download');
    await page.getByTestId('archive-singlefile-input').setInputFiles(filePath);
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toMatch(/\.wacz$/);

    const downloadPromise2 = page.waitForEvent('download');
    await page.getByTestId('archive-download-wacz').click();
    const download2 = await downloadPromise2;
    expect(download2.suggestedFilename()).toBe('test-capture-id.wacz');
});

test('Test tool chatbot', async ({page, authenticatedExtraFeaturesExtensionId}) => {
    // mock of the answer of the model
    await page.route('**completions**', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify(mockedChatbotResponse)
        });
    });

    // mock of the available model 
    await page.route('**models**', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                data: [
                    { id: 'mistral-7b' }
                ]
            }),
        });
    });

    await page.goto(`chrome-extension://${authenticatedExtraFeaturesExtensionId}/popup.html#/app/tools/chatbot`);

    //there is no need to select the model, because we mock only one model so it is selected automatically 

    await page.getByTestId('chatbot-select-prompt').click();
    await page.getByTestId('chatbot-fact-check-analysis').click();

    await page.locator('[data-testid="chatbot-input"] textarea:not([aria-hidden])').fill('Test chatbot');
    await page.getByTestId('chatbot-submit').click();

    await expect (page.getByTestId("chatbot-result")).toBeVisible();
})

test('Test tool ffmpeg toolkit', async ({page, authenticatedExtraFeaturesExtensionId}) => {
    const videoInputPath = path.resolve(__dirname, '../../tests-assets/test-metadata.mp4');

    await page.route('**extractvideo**', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'video/mp4'
        });
    });

    await page.route('**extractaudio**', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'audio/mpeg'
        });
    });

    await page.goto(`chrome-extension://${authenticatedExtraFeaturesExtensionId}/popup.html#/app/tools/ffmpegtoolkit`);

    await page.locator('input[type="file"]').setInputFiles(videoInputPath);

    await expect(page.getByTestId('ffmpegtoolkit-slider')).toBeVisible();

    await page.getByTestId('ffmpegtoolkit-submit').click();

    await expect(page.getByTestId('ffmpegtoolkit-video-container')).toBeVisible();

    // download video without options: open modal, confirm without checking anything
    await page.getByTestId('ffmpegtoolkit-downloadvideo-button').click();
    await expect(page.getByTestId('ffmpegtoolkit-download-modal')).toBeVisible();

    const downloadVideoPromise = page.waitForEvent('download');
    await page.getByTestId('ffmpegtoolkit-download-modal-confirm').click();
    const downloadVideo = await downloadVideoPromise;
    expect(downloadVideo.suggestedFilename()).toBe('test-metadata_extract.mp4');

    await expect(page.getByTestId('ffmpegtoolkit-download-modal')).not.toBeVisible();

    // download video with compress option
    await page.getByTestId('ffmpegtoolkit-downloadvideo-button').click();
    await expect(page.getByTestId('ffmpegtoolkit-download-modal')).toBeVisible();
    await page.getByTestId('ffmpegtoolkit-compress-checkbox').click();

    const downloadCompressedPromise = page.waitForEvent('download');
    await page.getByTestId('ffmpegtoolkit-download-modal-confirm').click();
    const downloadCompressed = await downloadCompressedPromise;
    expect(downloadCompressed.suggestedFilename()).toBe('test-metadata_extract_compressed.mp4');

    // download video with scale down option
    await page.getByTestId('ffmpegtoolkit-downloadvideo-button').click();
    await expect(page.getByTestId('ffmpegtoolkit-download-modal')).toBeVisible();
    await page.getByTestId('ffmpegtoolkit-scale-checkbox').click();

    const downloadScaledPromise = page.waitForEvent('download');
    await page.getByTestId('ffmpegtoolkit-download-modal-confirm').click();
    const downloadScaled = await downloadScaledPromise;
    expect(downloadScaled.suggestedFilename()).toBe('test-metadata_extract_scaled.mp4');

    // download video with both options
    await page.getByTestId('ffmpegtoolkit-downloadvideo-button').click();
    await expect(page.getByTestId('ffmpegtoolkit-download-modal')).toBeVisible();
    await page.getByTestId('ffmpegtoolkit-compress-checkbox').click();
    await page.getByTestId('ffmpegtoolkit-scale-checkbox').click();

    const downloadBothPromise = page.waitForEvent('download');
    await page.getByTestId('ffmpegtoolkit-download-modal-confirm').click();
    const downloadBoth = await downloadBothPromise;
    expect(downloadBoth.suggestedFilename()).toBe('test-metadata_extract_compressed_scaled.mp4');

    // download audio
    const downloadAudioPromise = page.waitForEvent('download');
    await page.getByTestId('ffmpegtoolkit-downloadaudio-button').click();
    const downloadAudio = await downloadAudioPromise;
    expect(downloadAudio.suggestedFilename()).toBe('test-metadata_extract.mp3');
})