/**
 * This file is a playwright test that verifies that the video's features function as they should. 
 * They are mostly generated by codegen, which you can use with the following command : 
 * 
 * node record-playwright.js
 * 
 */
import { test, expect } from './fixtures';
import path from 'path';
import singlefileResponse from '../../tests-assets/api-response/singlefile-to-wacz-response'

test('Test tool archive savepagenow', async ({page, authenticatedArchiveExtensionId, context}) => {
    await page.goto(`chrome-extension://${authenticatedArchiveExtensionId}/popup.html#/app/tools/archive`);

    await page.locator('[data-testid="archive-input"] input').fill('https://www.youtube.com/watch?v=QQFgQ1uBQtk');

    await page.getByTestId('archive-submit-savepagenow').click();

    await expect(page.getByTestId('archive-url-archive-card')).toBeVisible();

    const newTabPromise = page.context().waitForEvent('page');
    await page.getByTestId('archive-url-archive-card').getByRole('button', { name: /internet archive/i }).first().click();
    
    await expect.poll(async () => {
        return context.pages().length;
    }).toBe(3);
});

test('Test tool archive', async ({page, authenticatedArchiveExtensionId}) => {
    const buffer = Buffer.from('fake-wacz-content');

    await page.route('**singlefile**', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify(singlefileResponse)
        });
    });

    await page.route('**scoop**', async (route) => {
        const url = route.request().url();
        const method = route.request().method();

        if (method === 'POST' && url.endsWith('/capture')) {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ id: 'test-capture-id' })
            });
        } else if (url.includes('/capture/download/')) {
            await route.fulfill({
                status: 200,
                contentType: 'application/x-wacz',
                headers: {
                    'Content-Disposition': 'attachment; filename="archive.wacz"',
                    'Content-Length': buffer.length.toString(),
                },
                body: buffer
            });
        } else {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ status: 'COMPLETE' })
            });
        }
    });

    await page.goto(`chrome-extension://${authenticatedArchiveExtensionId}/popup.html#/app/tools/archive`);

    await page.locator('[data-testid="archive-input"] input').fill('https://www.youtube.com/watch?v=QQFgQ1uBQtk');

    await page.getByTestId('archive-submit-wacz').click();

    await expect(page.getByTestId("archive-download-webrecorder-link")).toBeVisible();
    await expect(page.getByTestId("archive-download-webrecorder-guide")).toBeVisible();
    await expect(page.getByTestId("archive-download-webrecorder-tuto")).toBeVisible();

    const filePath = path.resolve(__dirname, '../../tests-assets/test-singlefile-input.html');

    const downloadPromise = page.waitForEvent('download');
    await page.getByTestId('archive-singlefile-input').setInputFiles(filePath);
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toMatch(/\.wacz$/);

    const downloadPromise2 = page.waitForEvent('download');
    await page.getByTestId('archive-download-wacz').click();
    const download2 = await downloadPromise2;
    expect(download2.suggestedFilename()).toBe('test-capture-id.wacz');
});