/**
 * TODO : adding a test for the editor in magnifier, even if it's not an emergency because 
 * it's an external component.
 * This file is a playwright test that verifies that the search's features function as they should. 
 * They are mostly generated by codegen, which you can use with the following command : 
 * 
 * node record-playwright.js
 * 
 */
import { test, expect } from './fixtures';
import mockedMGTresponse from '../../tests-assets/api-response/machine-generated-text.json'
import mockedMGTresponseError from '../../tests-assets/api-response/machine-generated-text-error.json'

const MGT_INPUT_TEXT = `Artificial intelligence (AI) is rapidly transforming the way we live and work. From self-driving cars to medical diagnosis, AI systems are increasingly making decisions that were once exclusively the domain of humans. This technological revolution brings both tremendous opportunities and significant challenges that society must navigate carefully.`;

test('Test twitter search', async ({ page, context, extensionId }) => {
    await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/twitter`);
    await page.getByText("Accept").click();

    await page.locator('[data-testid="twitter-search-0"] input').fill('#AprilFool');
    await page.locator('[data-testid="twitter-search-1"] input').fill('Donald Trump');
    await page.locator('[data-testid="twitter-search-2"] input').fill('retweets');
    await page.locator('[data-testid="twitter-search-3"] input').fill('en');
    await page.locator('[data-testid="twitter-search-4"] input').fill('-22.912214,-43.230182,1km');
    await page.locator('[data-testid="twitter-search-5"] input').fill('Paris');
    await page.locator('[data-testid="twitter-search-6"] input').fill('15km'); 

    await page.getByTestId('twitter-since-date').fill('2023-10-25 10:00');
    await page.keyboard.press('Enter');

    await page.getByTestId('twitter-until-date').fill('2023-10-26 15:30');
    await page.keyboard.press('Enter');
    
    await page.getByTestId('twitter-radio-gmt').click();
    await page.getByTestId('twitter-radio-local').click();

    await page.getByTestId('twitter-submit').click();

    await expect.poll(async () => {
        return context.pages().length;
    }).toBe(3);
});

test('Test Machine generated text search', async ({ page, authenticatedBetaTesterExtensionId }) => {
    await page.route('**/kinit/mgt/detection', async(route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify(mockedMGTresponse)
        })
    })

    await page.goto(`chrome-extension://${authenticatedBetaTesterExtensionId}/popup.html#/app/tools/mgt`);

    await page.locator('[data-testid="mgt-input"] textarea:not([aria-hidden])').fill("test");

    await page.getByTestId('mgt-submit').click();

    await expect (page.getByTestId("mgt-results")).toBeVisible();
    await expect (page.getByTestId("mgt-results-gauge")).toBeVisible();

    await expect (page.getByTestId("mgt-results-highlight-text")).toBeVisible();
})

test('Test Machine generated text search error', async ({ page, authenticatedBetaTesterExtensionId }) => {
    await page.route('**/kinit/mgt/detection', async(route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify(mockedMGTresponseError)
        })
    })

    await page.goto(`chrome-extension://${authenticatedBetaTesterExtensionId}/popup.html#/app/tools/mgt`);

    await page.locator('[data-testid="mgt-input"] textarea:not([aria-hidden])').fill("test");

    await page.getByTestId('mgt-submit').click();

    await expect (page.getByTestId("mgt-errors")).toBeVisible();
})