/**
 * TODO : adding a test for the editor in magnifier, even if it's not an emergency because 
 * it's an external component.
 * This file is a playwright test that verifies that the search's features function as they should. 
 * They are mostly generated by codegen, which you can use with the following command : 
 * 
 * node record-playwright.js
 * 
 */
import { test, expect } from './fixtures';
import path from 'path';

test('Test twitter search', async ({ page, extensionId }) => {
    await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/twitter`);
    await page.getByText("Accept").click();

    await page.locator('[data-testid="twitter-search-0"] input').fill('#AprilFool');
    await page.locator('[data-testid="twitter-search-1"] input').fill('Donald Trump');
    await page.locator('[data-testid="twitter-search-2"] input').fill('retweets');
    await page.locator('[data-testid="twitter-search-3"] input').fill('en');
    await page.locator('[data-testid="twitter-search-4"] input').fill('-22.912214,-43.230182,1km');
    await page.locator('[data-testid="twitter-search-5"] input').fill('Paris');
    await page.locator('[data-testid="twitter-search-6"] input').fill('15km'); 

    await page.getByRole('dialog', { name: '* Since' })
          .getByRole('option', { name: '1 hours', exact: true })
          .click();
    await page.getByRole('button', { name: 'OK' }).click();

    await page.getByRole('dialog', { name: '* Until'  })
          .getByRole('option', { name: '2 hours', exact: true })
          .click();
    await page.getByRole('button', { name: 'OK' }).click();
    
    await page.getByTestId('twitter-radio-gmt').click();
    await page.getByTestId('twitter-radio-local').click();

    await page.getByTestId('twitter-submit').click();

    await expect.poll(async () => {
        return context.pages().length;
    }).toBe(1);
});