/**
 * This file is a playwright test that verifies that the video's features function as they should. 
 * They are mostly generated by codegen, which you can use with the following command : 
 * 
 * node record-playwright.js
 * 
 */
import { test, expect } from './fixtures';
import path from 'path';
import mockedKeyframesResponse from '../../tests-assets/api-response/keyframes-response.json'
import mockedDeepfakeResponse from '../../tests-assets/api-response/deepfake-response.json'
import mockedPoiForensicResponse from '../../tests-assets/api-response/poiforensic-response.json'

test(`Test tool analysis video`, async ({ page, extensionId }) => {
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/analysis`);
  // Accept local storage usage
  await page.getByText("Accept").click();

  //Test Youtube
  await  page.locator('[data-testid="analysis_video_input"] input').fill(
    "https://www.youtube.com/watch?v=WaaL75G0qu0"
  );
  await page.locator('[data-testid="analysis_video_submit"]').click();

  //Test results
  await expect(page.locator('[data-testid="analysis-yt-result"]')).toBeVisible();
  await page.locator('[data-testid="close-result-yt-btn"]').click();
  await expect(page.locator('[data-testid="analysis-yt-result"]')).toHaveCount(0);
});

// test generated with codegen
test('Test tool keyframes', async ({ page, extensionId }) => {
    await page.route('**/vera/public/kse_video_analysis', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify(mockedKeyframesResponse),
        });
    });

    await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/keyframes`);
    // Accept local storage usage
    await page.getByText("Accept").click();

    await page.locator('[data-testid="keyframes-input"] input').fill('https://www.youtube.com/watch?v=QQFgQ1uBQtk');

    await page.locator('[data-testid="keyframes-submit"]').click();

    // test of zoom in and out
    await page.locator('[data-testid="keyframes-zoomout"]').click();
    await page.locator('[data-testid="keyframes-zoomin"]').click();

    // test of detailed view
    await page.locator('[data-testid="keyframes-toggle-detailed"]').click();

    // test of download
    const downloadPromise = page.waitForEvent('download');
    await page.locator('[data-testid="keyframes-download"]').click();
    const download = await downloadPromise;

    await expect (page.locator('[data-testid="keyframes-results-general"]')).toBeVisible();
    await expect (page.locator('[data-testid="keyframes-results-audio"]')).toBeVisible();
    await expect (page.locator('[data-testid="keyframes-results-face"]')).toBeVisible();
    await expect (page.locator('[data-testid="keyframes-results-text"]')).toBeVisible();

    // test of closing button 
    await page.locator('[data-testid="keyframes-close"]').click();

    await expect (page.locator('[data-testid="keyframes-results-general"]')).toHaveCount(0);
    await expect (page.locator('[data-testid="keyframes-results-audio"]')).toHaveCount(0);
    await expect (page.locator('[data-testid="keyframes-results-face"]')).toHaveCount(0);
    await expect (page.locator('[data-testid="keyframes-results-text"]')).toHaveCount(0);
});

test('Test tool thumbnails', async ({ page, context, extensionId }) => {
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/thumbnails`);
  await page.getByText("Accept").click();

  // Counting tabs before submitting
  const countBefore = context.pages().length;

  await page.locator('[data-testid="thumbnails-input"] input').fill('https://www.youtube.com/watch?v=pjBG3sbPrq8');
  await page.locator('[data-testid="thumbnails-submit"]').click();
  
  // Verify that there is more tabs than before (TODO : make the test more precise, maybe counting the images identified and the checkbox checked, and verify that there 
  // is a number of tabs equals to the images multiplied by the checkbox)
  // Here we use a poll to wait for the tabs to open, and then do the assertion
  await expect.poll(async () => {
    return context.pages().length;
  }).toBeGreaterThan(countBefore);
  
  await page.locator('[data-testid="thumbnails-close"]').click();
});

test('Test tool metadata video', async ({ page, extensionId }) => {
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/metadata_image`);
  await page.getByText("Accept").click();

  const filePath = path.resolve(__dirname, '../../tests-assets/test-metadata.mp4');

  await page.locator('input[type="file"]').setInputFiles(filePath);

  await page.locator('[data-testid="metadata-submit"]').click();

  await expect (page.locator('[data-testid="c2pa-result"]')).toBeVisible();
});

test('Test tool deepfake video', async ({page, authenticatedBetaTesterExtensionId}) => {
  // mocking main route (TODO : put this json in test assets folder, in a dedicated file to mocked api response)
  await page.route('**/deepfake/videos/jobs?url=https:%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DyVEhrIMc-ps&services=faceswap_fsfm', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(mockedDeepfakeResponse)
    });
  });

  await page.goto(`chrome-extension://${authenticatedBetaTesterExtensionId}/popup.html#/app/tools/deepfakeVideo`);

  await page.locator('[data-testid="deepfake-input"] input').fill('https://www.youtube.com/watch?v=bPhUhypV27w');
  await page.getByTestId('deepfake-submit').click();

  await expect (page.getByTestId("deepfake-results")).toBeVisible();
  await expect (page.getByTestId("deepfake-video")).toBeVisible();
  await expect (page.getByTestId("deepfake-chart")).toBeVisible();
  await expect (page.getByTestId("deepfake-gauge")).toBeVisible();
  await expect (page.getByTestId("deepfake-keyframes")).toBeVisible();

  await page.getByTestId('deepfake-close').click();
  await expect (page.getByTestId("deepfake-results")).toHaveCount(0);
});

test('Test tool poi forensic video', async ({page, authenticatedExtraFeaturesExtensionId}) => {
  await page.route('**/deepfake/videos/jobs?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DSOo7fHT_Na0&services=poi_forensics&services_parameters=%7B%22poi_forensics%22%3A%7B%22poi%22%3A%22Macron%22%2C%22modality%22%3A%22audiovideo%22%7D%7D', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(mockedPoiForensicResponse)
    });
  });

  await page.goto(`chrome-extension://${authenticatedExtraFeaturesExtensionId}/popup.html#/app/tools/poiforensic`);

  await page.locator('[data-testid="poiforensic-input"] input').fill('https://www.youtube.com/watch?v=SOo7fHT_Na0');
  await page.getByTestId('poiforensic-submit').click();

  await expect (page.getByTestId("poiforensic-results")).toBeVisible();
  await expect (page.getByTestId("poiforensic-video")).toBeVisible();
  await expect (page.getByTestId("poiforensic-chart")).toBeVisible();

  await page.getByTestId('poiforensic-close').click();
  await expect (page.getByTestId("poiforensic-results")).toHaveCount(0);
});


