/**
 * This file is a playwright test that verifies that the video's features function as they should. 
 * They are mostly generated by codegen, which you can use with the following command : 
 * 
 * node record-playwright.js
 * 
 */
import { test, expect } from './fixtures';
import path from 'path';

test(`Test tool analysis video`, async ({ page, extensionId }) => {
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/analysis`);
  // Accept local storage usage
  await page.getByText("Accept").click();

  //Test Youtube
  await  page.locator('[data-testid="analysis_video_input"] input').fill(
    "https://www.youtube.com/watch?v=WaaL75G0qu0"
  );
  await page.locator('[data-testid="analysis_video_submit"]').click();

  //Test results
  await expect(page.locator('[data-testid="analysis-yt-result"]')).toBeVisible();
  await page.locator('[data-testid="close-result-yt-btn"]').click();
  await expect(page.locator('[data-testid="analysis-yt-result"]')).toHaveCount(0);
});

// test generated with codegen
test('Test tool keyframes', async ({ page, extensionId }) => {
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/keyframes`);
  // Accept local storage usage
  await page.getByText("Accept").click();

  await page.locator('[data-testid="keyframes-input"] input').fill('https://www.youtube.com/watch?v=QQFgQ1uBQtk');

  await page.locator('[data-testid="keyframes-submit"]').click();
  
  // test of zoom in and out
  await page.locator('[data-testid="keyframes-zoomout"]').click();
  await page.locator('[data-testid="keyframes-zoomin"]').click();

  // test of detailed view
  await page.locator('[data-testid="keyframes-toggle-detailed"]').click();

  // test of download
  const downloadPromise = page.waitForEvent('download');
  await page.locator('[data-testid="keyframes-download"]').click();
  const download = await downloadPromise;
  
  await expect (page.locator('[data-testid="keyframes-results-general"]')).toBeVisible();
  await expect (page.locator('[data-testid="keyframes-results-audio"]')).toBeVisible();
  await expect (page.locator('[data-testid="keyframes-results-face"]')).toBeVisible();
  await expect (page.locator('[data-testid="keyframes-results-text"]')).toBeVisible();

  // test of closing button 
  await page.locator('[data-testid="keyframes-close"]').click();

  await expect (page.locator('[data-testid="keyframes-results-general"]')).toHaveCount(0);
  await expect (page.locator('[data-testid="keyframes-results-audio"]')).toHaveCount(0);
  await expect (page.locator('[data-testid="keyframes-results-face"]')).toHaveCount(0);
  await expect (page.locator('[data-testid="keyframes-results-text"]')).toHaveCount(0);
});

test('Test tool thumbnails', async ({ page, context, extensionId }) => {
  // Navigate to the demo page
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/thumbnails`);
  // Accept local storage usage
  await page.getByText("Accept").click();

  // Counting tabs before submitting
  const countBefore = context.pages().length;

  await page.locator('[data-testid="thumbnails-input"] input').fill('https://www.youtube.com/watch?v=pjBG3sbPrq8');
  await page.locator('[data-testid="thumbnails-submit"]').click();
  
  // Verify that there is more tabs than before (TODO : make the test more precise, maybe counting the images identified and the checkbox checked, and verify that there 
  // is a number of tabs equals to the images multiplied by the checkbox)
  // Here we use a poll to wait for the tabs to open, and then do the assertion
  await expect.poll(async () => {
    return context.pages().length;
  }).toBeGreaterThan(countBefore);
  
  await page.locator('[data-testid="thumbnails-close"]').click();
});

test('Test tool metadata video', async ({ page, extensionId }) => {
  await page.goto(`chrome-extension://${extensionId}/popup.html#/app/tools/metadata_image`);
  await page.getByText("Accept").click();

  const filePath = path.resolve(__dirname, '../../tests-assets/test-metadata.mp4');

  await page.locator('input[type="file"]').setInputFiles(filePath);

  await page.locator('[data-testid="metadata-submit"]').click();

  await expect (page.locator('[data-testid="c2pa-result"]')).toBeVisible();
});


