/**
 * Authentication error codes.
 */

export const ERR_AUTH_UNKNOWN_ERROR = "ERR_AUTH_UNKNOWN_ERROR";
export const ERR_AUTH_INVALID_PARAMS = "ERR_AUTH_INVALID_PARAMS";
export const ERR_AUTH_BAD_REQUEST = "ERR_AUTH_BAD_REQUEST";
export const ERR_AUTH_SERVER_ERROR = "ERR_AUTH_SERVER_ERROR";
export const ERR_AUTH_ABORT_ERROR = "ERR_AUTH_ABORT_ERROR";
export const ERR_AUTH_INVALID_TOKEN = "ERR_AUTH_INVALID_TOKEN";
export const ERR_AUTH_INVALID_CREDENTIALS = "ERR_AUTH_INVALID_CREDENTIALS";
export const ERR_AUTH_INVALID_USER_STATE = "ERR_AUTH_INVALID_USER_STATE";
export const ERR_AUTH_USER_EXPIRED = "ERR_AUTH_USER_EXPIRED";
export const ERR_AUTH_SESSION_EXPIRED = "ERR_AUTH_SESSION_EXPIRED";

export default {
  ERR_AUTH_UNKNOWN_ERROR,
  ERR_AUTH_INVALID_PARAMS,
  ERR_AUTH_BAD_REQUEST,
  ERR_AUTH_SERVER_ERROR,
  ERR_AUTH_INVALID_TOKEN,
  ERR_AUTH_INVALID_CREDENTIALS,
  ERR_AUTH_INVALID_USER_STATE,
  ERR_AUTH_USER_EXPIRED,
  ERR_AUTH_SESSION_EXPIRED
};
